### ISSUE TITLE
Automate linting & tests with GitHub actions

### ISSUE THREAD

**Issue by alan-cooney** [rudderlabs/rudder-sdk-js#276]
It would be nice if PRs are linted and checked automatically, so that for small changes you don't have to pull down the repo locally and run everything yourself. The repo already has 1 GitHub action, so it would be trivial to add these two more, e.g. something roughly like this:

```yml
name: lintTest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lintTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Yarn use cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        env:
          cache-name: cache-node-modules
      - name: Install dependencies
        run: yarn install
      - name: Checking for Linting Errors
        run: yarn lint
      - name: Run jest tests
        run: yarn coverage
```

Note the package lock file needs to be committed for caching to work, but caching isn't strictly necessary. It's good practice to commit up the lock file however anyway, so no harm from doing that.
